PcaSoundCloud.Web/Controllers/SearchController.cs
using System.Web.Mvc;
using PcaSoundCloud.Shared;

namespace PcaSoundCloud.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ITrackService _service;

        public SearchController(ITrackService service)
        {
            _service = service;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SearchMusic(string userName)
        {
            var results = _service.Search(new TrackCriteria { SearchText = userName, MaxResults = 5});
            return Json(new { tracks = results }, JsonRequestBehavior.AllowGet);
        }
    }
}

PcaSoundCloud.Web/Controllers/TrackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PcaSoundCloud.Core;
using PcaSoundCloud.Shared;

namespace PcaSoundCloud.Web.Controllers
{
    public class TrackController : Controller
    {
        private readonly ITrackService _trackService;

        public TrackController(ITrackService trackService)
        {
            _trackService = trackService;            
        }

        //
        // GET: /Track/

        public ActionResult Index(int i)
        {            
            return View(_trackService.GetTrack(i));
        }
    }
}

PcaSoundCloud.Web/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-app="Search" ng-controller="searchCtrl">
    <h2>Search Music</h2>
    
        
        
    
    <form>
        <div class="input-group">
            <input autofocus type="text" name="search" ng-model="searchString" class="form-control" />
            <span class="input-group-btn">
                <button type="submit" ng-click="search(searchString)" class="btn btn-default">Search</button>
            </span>
        </div>
    </form>

    <div ng-repeat="track in tracks" class="track row">
        <div class="col-lg-2">
            <img ng-src="{{track.User.AvatarUrl}}" alt="user url" />
        </div>
        <div class="col-lg-10">
            <a href="@Url.Action("Index", "Track")?i={{track.Id}}">
                <h4>{{track.Title}}</h4>
            </a>
            {{track.Permalinkurl}}
            <p>
                {{track.Description}}
            </p>
        </div>

    </div>
</div>

@section scripts
{
    <script>
        angular.module('Search', [])
            .controller('searchCtrl', ['$scope', '$http', function ($scope, $http) {
                $scope.searchString = '';
                $scope.expectedVarName = 'userName';

                $scope.search = function (searchString) {
                    $http.get('/search/searchmusic?' + $scope.expectedVarName + '=' + searchString).success(function (response) {
                        $scope.tracks = response.tracks;
                    });
                };
            }]);
    </script>
}